[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hongyu", email = "hongyu@imandra.ai" }
]
requires-python = ">=3.13"
dependencies = [
    "imandrax-codegen-py",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
imandrax-codegen-py = { workspace = true }

[dependency-groups]
dev = [
    "dotenv>=0.9.9",
    "ipykernel>=7.0.1",
]
