[project]
name = "imandrax-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hongyu", email = "hongyu@imandra.ai" }
]
requires-python = ">=3.12"
dependencies = [
    "imandrax-api-models>=1.0.0",
    "iml-query>=0.4.1",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.ruff.format]
quote-style = "single"
